data:
  train_files: LMMs-Lab-Turtle/Vision-SR1-47K@train
  val_files: zli12321/mmstar@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 12800
  max_response_length: 4096
  rollout_batch_size: 512
  mini_rollout_batch_size: null
  val_batch_size: 1024
  format_prompt: ./vision_sr1/format_prompt/see_think.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 2
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
      lora:
        rank: 0
        alpha: 64
        target_modules: all-linear
        exclude_modules: .*visual.*
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 8
    temperature: 1.0
    top_p: 0.99
    max_num_batched_tokens: 16896
    max_model_len: 16896
    limit_images: 0
    gpu_memory_utilization: 0.35
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.0
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_function: ./vision_sr1/reward_function/self_reward.py:compute_score

trainer:
  total_epochs: 1
  max_steps: null
  project_name: vision_sr1
  experiment_name: qwen2_5_vl_7b_self_reward_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20
  val_freq: 5
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 20
  save_limit: -1
  save_model_only: false
  save_checkpoint_path: ./saves/self_reward
  load_checkpoint_path: null
  find_last_checkpoint: true
